"""Generate relocation-aware award prefixes from the pinned, locally owned PE.

This reads the executable without loading it. Normal builds use the reviewed
include already in src/bridge; generated files and audit metadata default to
ignored local/. Use --check to compare the current source without writing it.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct

REPO = Path(__file__).resolve().parents[2]
EXPECTED_SHA256 = "dc04aee5a3debc3f1ad4c1a937460e99a29b9bd3bc285008be83615dd5e59a37"
ADDRESSES = (0xC02FF0, 0xC042A0, 0xF67D40, 0xB1FD00, 0xD2E2E0,
             0xD39360, 0xD45740, 0xD2E360, 0xD2C490, 0xD2C940,
             0xB639D0, 0xB639F0, 0xD2D560, 0xD2D0B0, 0xD2E980,
             0xD2E380, 0xD2E720)
HEADER = "// Generated by tools/native/generate-award-prefixes.py. Pinned SHA-256, exact ASLR relocation.\n"


def generate(data):
    digest = hashlib.sha256(data).hexdigest()
    if digest != EXPECTED_SHA256:
        raise ValueError("Unknown executable SHA-256; no files generated")
    nt = struct.unpack_from("<I", data, 0x3c)[0]
    count = struct.unpack_from("<H", data, nt + 6)[0]
    optional = nt + 24
    length = struct.unpack_from("<H", data, nt + 20)[0]
    if (data[nt:nt + 4] != b"PE\0\0"
            or struct.unpack_from("<H", data, nt + 4)[0] != 0x14c
            or struct.unpack_from("<H", data, optional)[0] != 0x10b
            or struct.unpack_from("<I", data, optional + 28)[0] != 0x400000):
        raise ValueError("Pinned executable PE identity does not match")
    sections = [struct.unpack_from("<8sIIII", data, optional + length + i * 40)
                for i in range(count)]

    def offset(rva, size=1):
        for _, _, start, raw_size, raw in sections:
            if start <= rva and rva + size <= start + raw_size:
                return raw + rva - start
        raise ValueError(f"Unmapped RVA {rva:x}")

    reloc_rva, reloc_size = struct.unpack_from("<II", data, optional + 96 + 5 * 8)
    at = offset(reloc_rva, reloc_size)
    end = at + reloc_size
    relocations = set()
    while at < end:
        page, size = struct.unpack_from("<II", data, at)
        if size < 8 or size % 2 or at + size > end:
            raise ValueError("Invalid relocation block")
        for n in range((size - 8) // 2):
            word = struct.unpack_from("<H", data, at + 8 + n * 2)[0]
            if word >> 12 == 3:
                relocations.add(page + (word & 0xfff))
            elif word >> 12 != 0:
                raise ValueError("Unsupported relocation type")
        at += size
    prefixes, lines = [], []
    for va in ADDRESSES:
        rva = va - 0x400000
        fixups = [item - rva for item in sorted(relocations) if rva <= item < rva + 16]
        length = max([16] + [n + 4 for n in fixups])
        start = offset(rva, length)
        code = data[start:start + length]
        mask = sum(1 << n for n in fixups)
        prefixes.append(dict(va=hex(va), rva=hex(rva), bytes=code.hex(), highlow_offsets=fixups))
        lines.append('    {0x%x,{%s},0x%x,%d},' %
                     (rva, ','.join('0x%02x' % byte for byte in code), mask, length))
    report = dict(
        evidence_class="STATIC_PREFIX_AND_ABI_NOT_NATIVE_ACCEPTANCE",
        executable_sha256=digest, prefixes=prefixes,
        abi={'owned': 'thiscall bool(Spatial*)', 'amount': 'thiscall float(Animal*,bool), ret4/x87',
             'getters': 'thiscall pointer(Manager*), no stack args', 'display': 'thiscall void(Display*,float), ret4',
             'action': 'thiscall void(Strategy*,uint32,void*), ret8', 'mode_update': 'thiscall void(Strategy*,float,float), ret8',
             'goal': 'cdecl float(), x87', 'counter': 'state+0, native 40-byte deque+4, native 32-byte timer+0x30; size0x50, align8',
             'counter_tick': 'thiscall void(counter*,uint32), ret4; original ignores supplied time and uses its native timer'},
        owned_predicate_call_returns=['0x807AC9', '0x807B87'], amount_call_return='0x807BE4',
        dna_call_return='0x807BF1', combat_player_get_return='0x807C0A', world_goal_get_return='0x945AA9')
    return HEADER + '\n'.join(lines) + '\n', report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--executable', type=Path, required=True)
    parser.add_argument('--output', type=Path, default=REPO / 'local/native-prefixes/native_award_prefixes.inc')
    parser.add_argument('--report', type=Path, default=REPO / 'local/native-prefixes/binding-audit.json')
    parser.add_argument('--check', action='store_true', help='Compare against committed prefixes without writing files')
    args = parser.parse_args()
    content, report = generate(args.executable.read_bytes())
    if args.check:
        expected = (REPO / 'src/bridge/native_award_prefixes.inc').read_text(encoding='utf-8-sig')
        if content != expected:
            raise ValueError('Generated prefixes differ from the reviewed source')
    else:
        if args.output.resolve() == args.report.resolve():
            raise ValueError('The source and report output paths must differ')
        if args.output.exists() or args.report.exists():
            raise ValueError('Use fresh output paths; existing files are never overwritten')
        for path in (args.output, args.report):
            path.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open('x', encoding='utf-8', newline='\n') as stream:
            stream.write(content)
        with args.report.open('x', encoding='utf-8', newline='\n') as stream:
            json.dump(report, stream, indent=2)
            stream.write('\n')
    print(json.dumps({'prefixes': len(report['prefixes']), 'check_only': args.check,
                      'highlow_words': sum(len(p['highlow_offsets']) for p in report['prefixes']),
                      'native_game': 'NOT_RUN'}))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
