#include "coordinator.h"
#include "tls.h"
#include "channel.h"
#include <chrono>
#include <cstring>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <thread>

using namespace sporemp::network;
namespace {
int assertions=0;
void check(bool pass,const char* message){++assertions;if(!pass)throw std::runtime_error(message);}
Digest digest(uint8_t v){Digest d{};d.fill(v);return d;}
SessionConfig settings(){SessionConfig c;c.identity={digest(1),digest(2),digest(3),digest(4)};c.authority=digest(10);c.player1=digest(11);c.player2=digest(12);c.epoch=42;return c;}
Entity entity(uint64_t id,uint64_t owner){Entity e;e.id=id;e.generation=1;e.owner=owner;e.tick=1;e.native_id=uint32_t(id);e.herd_native_id=8;e.species_instance=9;e.species_type=10;e.species_group=11;e.archetype=12;e.x=1;e.y=2;e.z=3;e.health=100;e.energy=50;e.hunger=30;e.dna=8.75f;return e;}
void codec_tests(){
    Packet p;p.kind=Kind::entity;p.sequence=123;p.session=42;p.scene=4;p.baseline=5;p.player=2;p.identity=settings().identity;p.credential=digest(99);p.entity=entity(19,2);p.entity.vx=4;p.entity.vy=5;p.entity.vz=6;p.request=991;
    Wire w=encode(p);Packet result;std::string error;check(decode(w.data(),w.size(),result,error),"roundtrip_decode");check(result.entity.id==19&&result.entity.dna==8.75f&&result.entity.vz==6&&result.request==991&&result.identity==p.identity,"roundtrip_fields");
    for(size_t n=0;n<packet_bytes;++n)check(!decode(w.data(),n,result,error),"every_truncation_rejected");check(!decode(w.data(),packet_bytes+1,result,error),"oversize_rejected");
    for(size_t offset:{size_t(0),size_t(4),size_t(8),size_t(12),size_t(16),size_t(20),size_t(24),size_t(31),size_t(383)}){Wire bad=w;bad[offset]=255;check(!decode(bad.data(),bad.size(),result,error),"header_enum_or_reserved_rejected");}
    p.entity.x=std::numeric_limits<float>::quiet_NaN();w=encode(p);check(!decode(w.data(),w.size(),result,error),"nan_rejected");p.entity.x=1;p.entity.owner=3;w=encode(p);check(!decode(w.data(),w.size(),result,error),"invalid_entity_owner");p.entity=entity(19,2);p.kind=Kind::action;p.direction=3;w=encode(p);check(decode(w.data(),w.size(),result,error),"native_direction3");p.direction=4;w=encode(p);check(!decode(w.data(),w.size(),result,error),"invalid_direction");p.direction=0;p.verb=Verb(4);w=encode(p);check(!decode(w.data(),w.size(),result,error),"retire_not_exposed");
    Digest d;check(parse_hex(hex(digest(97)),d)&&d==digest(97),"hex_roundtrip");check(!parse_hex(std::string(64,'z'),d)&&!parse_hex("abc",d),"invalid_hex");
}
struct Fixture {
    SessionConfig config=settings();Session session{config};uint64_t seq[16]{};
    std::vector<Dispatch> send(uint64_t c,Packet p){p.sequence=++seq[c];p.session=p.kind==Kind::hello?0:config.epoch;return session.receive(c,p);}
    std::vector<Dispatch> join(uint64_t c,Role role,uint64_t player=0){check(session.connect(c),"session_connect");Packet p;p.kind=Kind::hello;p.role=role;p.identity=config.identity;p.credential=role==Role::authority?config.authority:player==1?config.player1:config.player2;return send(c,p);}
    std::vector<Dispatch> baseline(uint64_t scene=1,uint64_t baseline_id=1){Packet p;p.scene=scene;p.baseline=baseline_id;p.kind=Kind::scene_begin;p.count=2;send(1,p);p.kind=Kind::entity;p.entity=entity(101,1);send(1,p);p.entity=entity(102,2);send(1,p);p.kind=Kind::scene_end;return send(1,p);}
};
uint64_t baseline_id(const std::vector<Dispatch>& v,uint64_t c){for(const auto& d:v)if(d.connection==c&&d.packet.kind==Kind::scene_begin)return d.packet.baseline;return 0;}
bool rejected(const std::vector<Dispatch>& v,Error e){return !v.empty()&&v.back().packet.kind==Kind::reject&&v.back().packet.error==e;}
bool action_refused(const std::vector<Dispatch>& v,Error e){return v.size()==1&&v[0].packet.kind==Kind::action_result&&v[0].packet.error==e&&!v[0].close;}
void session_tests(){
    Fixture f;check(f.join(1,Role::authority).front().packet.player==0,"authority_authenticated");check(f.join(2,Role::player,1).front().packet.player==1,"first_player_identity");check(f.join(3,Role::player,2).front().packet.player==2,"second_player_identity");auto b=f.baseline();uint64_t b1=baseline_id(b,2),b2=baseline_id(b,3);check(b.size()==8&&b1&&b2&&b1!=b2&&f.session.entity_count()==2,"full_independent_baselines");
    Packet action;action.kind=Kind::action;action.scene=1;action.baseline=b1;action.entity=entity(101,1);action.verb=Verb::jump;action.player=999;check(action_refused(f.send(2,action),Error::not_ready),"action_waits_baseline_ack");Packet ack;ack.kind=Kind::baseline_ack;ack.scene=1;ack.baseline=b1;check(f.send(2,ack).empty(),"baseline_ack");auto routed=f.send(2,action);check(routed.size()==1&&routed[0].connection==1&&routed[0].packet.player==1&&routed[0].packet.baseline==1&&routed[0].packet.request!=0,"authenticated_owner_routing");action.entity.id=102;check(rejected(f.send(2,action),Error::ownership),"wrong_actor_denied");action.entity.id=101;action.baseline=b1+99;check(action_refused(f.send(2,action),Error::stale),"wrong_baseline_denied");
    f.session.disconnect(2);auto reconnect=f.join(4,Role::player,1);uint64_t fresh=baseline_id(reconnect,4);check(reconnect.front().packet.player==1&&fresh>b2&&f.session.entity_count()==2,"reconnect_identity_fresh_baseline_no_duplicate");ack.baseline=b1;check(f.send(4,ack).empty(),"reconnect_old_ack_ignored");action.scene=1;action.baseline=fresh;action.entity=entity(101,1);check(action_refused(f.send(4,action),Error::not_ready),"obsolete_ack_does_not_restore_readiness");
    Packet update;update.kind=Kind::despawn;update.scene=1;update.baseline=1;update.entity=entity(101,1);update.entity.tick=2;check(f.send(1,update).size()==2&&f.session.entity_count()==1,"reliable_despawn");update.kind=Kind::motion;update.entity.tick=3;check(rejected(f.send(1,update),Error::stale)&&f.session.entity_count()==1,"motion_cannot_resurrect");update.kind=Kind::entity;check(rejected(f.send(1,update),Error::stale),"old_generation_spawn_denied");update.entity.generation=2;check(f.send(1,update).size()==2&&f.session.entity_count()==2,"new_generation_spawn");update.kind=Kind::motion;update.entity.owner=2;update.entity.tick=4;check(rejected(f.send(1,update),Error::stale),"motion_cannot_change_owner");update.entity.owner=1;update.entity.tick=2;check(rejected(f.send(1,update),Error::stale),"out_of_order_motion_denied");update.entity.tick=4;update.entity.native_id=999;check(rejected(f.send(1,update),Error::ownership),"motion_cannot_replace_fingerprint");
    auto second=f.baseline(2,2);check(f.session.scene()==2&&baseline_id(second,4)>fresh,"new_scene_new_baseline");update.scene=1;check(rejected(f.send(1,update),Error::stale),"old_scene_motion_denied");auto lost=f.session.disconnect(1);check(lost.size()==2&&lost[0].packet.error==Error::authority_lost,"authority_disconnect_fences_clients");
    Fixture bad;check(bad.session.connect(1),"bad_connect");Packet hello;hello.kind=Kind::hello;hello.identity=bad.config.identity;hello.credential=digest(77);check(rejected(bad.send(1,hello),Error::authentication),"wrong_invite_rejected");hello.credential=bad.config.player1;hello.identity.content=digest(99);check(rejected(bad.send(1,hello),Error::incompatible),"content_mismatch_rejected");hello.identity=bad.config.identity;hello.identity.fixture=digest(98);check(rejected(bad.send(1,hello),Error::incompatible),"fixture_mismatch_rejected");hello.identity=bad.config.identity;auto accepted=bad.send(1,hello);check(accepted.front().packet.player==1,"valid_after_bad_fixture_in_pure_policy");hello.sequence=1;hello.session=42;check(rejected(bad.session.receive(1,hello),Error::stale),"replay_rejected");
    Fixture empty;empty.join(1,Role::authority);empty.baseline();Packet exit;exit.kind=Kind::scene_begin;exit.scene=2;exit.baseline=2;empty.send(1,exit);exit.kind=Kind::scene_end;check(empty.send(1,exit).empty()&&empty.session.entity_count()==0,"empty_scene_exit");
    Fixture full;for(uint64_t c=1;c<=8;++c)check(full.session.connect(c),"bounded_connection_capacity");check(!full.session.connect(9),"ninth_connection_rejected");
    detail::Channel queue;Packet queued;for(size_t i=0;i<queue_capacity;++i)if(!queue.send(queued))throw std::runtime_error("queue_premature_limit");check(!queue.send(queued),"outgoing_queue_exhaustion_fails_closed");
    Fixture duplicate;duplicate.join(1,Role::authority);duplicate.join(2,Role::player,1);auto db=duplicate.baseline();Packet da;da.kind=Kind::baseline_ack;da.scene=1;da.baseline=baseline_id(db,2);duplicate.send(2,da);da.kind=Kind::action;da.entity=entity(101,1);da.request=10;check(duplicate.send(2,da).front().connection==1,"new_action_request");check(rejected(duplicate.send(2,da),Error::stale),"duplicate_action_request_not_executed");
    std::vector<Dispatch> last;for(size_t i=0;i<128;++i){da.request++;last=duplicate.send(2,da);}check(rejected(last,Error::capacity),"per_player_action_rate_bounded");
    Fixture rebase;rebase.join(1,Role::authority);rebase.join(2,Role::player,1);auto rb=rebase.baseline();uint64_t rb_old=baseline_id(rb,2);
    Packet old_ack;old_ack.kind=Kind::baseline_ack;old_ack.scene=1;old_ack.baseline=rb_old;rebase.send(2,old_ack);
    Packet begin;begin.kind=Kind::scene_begin;begin.scene=2;begin.baseline=2;begin.count=2;rebase.send(1,begin);
    Packet late;late.kind=Kind::action;late.scene=1;late.baseline=rb_old;late.request=900;late.entity=entity(101,1);late.player=999;
    auto refused=rebase.send(2,late);check(action_refused(refused,Error::not_ready)&&refused[0].packet.request==900&&refused[0].packet.player==1&&refused[0].packet.scene==1&&refused[0].packet.baseline==rb_old,"in_flight_action_during_rebase_correlated_refusal");
    check(rebase.send(2,old_ack).empty(),"in_flight_ack_during_rebase_ignored");
    begin.kind=Kind::entity;begin.entity=entity(101,1);rebase.send(1,begin);begin.entity=entity(102,2);rebase.send(1,begin);begin.kind=Kind::scene_end;auto committed=rebase.send(1,begin);uint64_t rb_new=baseline_id(committed,2);check(rb_new>rb_old,"rebase_fresh_baseline_after_in_flight_action");
    check(rebase.send(2,old_ack).empty(),"obsolete_ack_after_rebase_ignored");late.scene=2;late.baseline=rb_new;late.request=901;check(action_refused(rebase.send(2,late),Error::not_ready),"rebase_requires_fresh_ack");old_ack.scene=2;old_ack.baseline=rb_new;rebase.send(2,old_ack);late.request=902;auto good=rebase.send(2,late);check(good.size()==1&&good[0].connection==1&&good[0].packet.kind==Kind::action,"fresh_ack_restores_action_routing_after_rebase");
}
bool await_packet(Peer& peer,Kind kind,Packet& packet,std::string& error,unsigned milliseconds=5000){auto end=std::chrono::steady_clock::now()+std::chrono::milliseconds(milliseconds);Event e;while(std::chrono::steady_clock::now()<end){while(peer.poll(e)){if(e.kind==EventKind::packet){if(e.packet.kind==kind){packet=e.packet;return true;}if(e.packet.kind==Kind::reject){error=error_name(e.packet.error);return false;}}if(e.kind==EventKind::disconnected){error=e.detail;return false;}}std::this_thread::sleep_for(std::chrono::milliseconds(1));}error="await_packet_timeout";return false;}
void require_packet(Peer& peer,Kind kind,Packet& p,const char* message){std::string error;bool got=await_packet(peer,kind,p,error);if(!got)std::cerr<<message<<": "<<error<<'\n';check(got,message);}
void tls_tests(){
    CoordinatorConfig config;config.port=0;config.session=settings();Coordinator server;std::string error;bool started=server.start(config,error);if(!started)std::cerr<<"TLS server: "<<error<<'\n';check(started,"real_tls_listener");
    std::atomic<bool> stop{false};std::thread pump([&]{CoordinatorEvent e;while(!stop){while(server.poll(e)){}std::this_thread::sleep_for(std::chrono::milliseconds(1));}});
    try {
        auto aconfig=server.peer_config(Role::authority),pconfig=server.peer_config(Role::player,1),qconfig=server.peer_config(Role::player,2);
        check(pconfig.certificate_pin!=Digest{}&&pconfig.credential!=qconfig.credential&&pconfig.credential!=aconfig.credential,"tls_fresh_pin_distinct_credentials");
        Peer authority,p1,p2;check(authority.start(aconfig,error),"authority_network_start");check(p1.start(pconfig,error),"player1_network_start");check(p2.start(qconfig,error),"player2_network_start");Packet ap,pp,qp;require_packet(authority,Kind::welcome,ap,"authority_tls_welcome");require_packet(p1,Kind::welcome,pp,"player1_tls_welcome");require_packet(p2,Kind::welcome,qp,"player2_tls_welcome");check(pp.player==1&&qp.player==2&&pp.session==qp.session&&ap.session==pp.session,"real_tls_shared_session_distinct_players");
        Packet b;b.kind=Kind::scene_begin;b.scene=1;b.baseline=1;b.count=static_cast<uint32_t>(max_entities);check(authority.send(b),"send_baseline_begin");b.kind=Kind::entity;b.entity=entity(101,1);authority.send(b);b.entity=entity(102,2);authority.send(b);for(size_t i=2;i<max_entities;++i){b.entity=entity(1000+i,0);check(authority.send(b),"maximum_scene_entity_enqueued");}b.kind=Kind::scene_end;authority.send(b);require_packet(p1,Kind::scene_end,pp,"p1_actual_tls_baseline");require_packet(p2,Kind::scene_end,qp,"p2_actual_tls_baseline");check(pp.baseline!=qp.baseline&&pp.count==max_entities&&qp.count==max_entities,"real_maximum_scene_independent_baselines");Packet ack;ack.kind=Kind::baseline_ack;ack.scene=1;ack.baseline=pp.baseline;p1.send(ack);Packet act=ack;act.kind=Kind::action;act.entity=entity(101,1);act.verb=Verb::jump;act.player=999;p1.send(act);require_packet(authority,Kind::action,ap,"actual_action_to_authority");check(ap.player==1&&ap.entity.owner==1&&ap.baseline==1&&ap.request!=0,"actual_authenticated_action_owner");
        act.entity.id=102;p1.send(act);require_packet(p1,Kind::reject,ap,"actual_wrong_owner_rejection");check(ap.error==Error::ownership,"actual_wrong_owner_reason");
        auto old_baseline=pp.baseline;p1.stop();Peer resumed;check(resumed.start(pconfig,error),"reconnect_start");require_packet(resumed,Kind::welcome,pp,"reconnect_welcome");check(pp.player==1,"reconnect_same_player");require_packet(resumed,Kind::scene_end,pp,"reconnect_fresh_baseline");check(pp.baseline>old_baseline,"reconnect_fresh_baseline_id");
        Peer wrong_pin;auto bad=pconfig;bad.certificate_pin[0]^=1;check(wrong_pin.start(bad,error),"bad_pin_start");check(!await_packet(wrong_pin,Kind::welcome,ap,error)&&error=="certificate_pin_or_validity_mismatch","real_wrong_pin_rejected");wrong_pin.stop();
        Peer wrong_secret;bad=pconfig;bad.credential[0]^=1;check(wrong_secret.start(bad,error),"bad_secret_start");require_packet(wrong_secret,Kind::reject,ap,"real_wrong_secret_rejected");check(ap.error==Error::authentication,"real_wrong_secret_reason");wrong_secret.stop();
        Peer mismatch;bad=pconfig;bad.identity.build[0]^=1;check(mismatch.start(bad,error),"bad_build_start");require_packet(mismatch,Kind::reject,ap,"real_wrong_build_rejected");check(ap.error==Error::incompatible,"real_wrong_build_reason");mismatch.stop();
        auto raw_socket=detail::connect_socket(pconfig.host,pconfig.port,stop,error);check(raw_socket!=INVALID_SOCKET,"malformed_tls_socket");{detail::TlsStream raw(raw_socket);check(raw.handshake(false,nullptr,pconfig.certificate_pin,pconfig.host,stop,error),"malformed_real_tls_handshake");Packet h;h.kind=Kind::hello;h.sequence=1;h.identity=pconfig.identity;h.credential=pconfig.credential;Wire malformed=encode(h);malformed[4]=255;malformed[5]=255;check(raw.send(malformed.data(),malformed.size(),error),"oversized_message_sent_inside_tls");std::vector<uint8_t> bytes;bool open=true;auto end=std::chrono::steady_clock::now()+std::chrono::seconds(3);while(open&&std::chrono::steady_clock::now()<end){open=raw.receive(bytes,error);std::this_thread::sleep_for(std::chrono::milliseconds(2));}check(!open,"real_oversized_frame_connection_closed");}
        resumed.stop();p2.stop();authority.stop();
    }catch(...){stop=true;pump.join();server.stop();throw;}
    stop=true;pump.join();server.stop();
}
}
int main(){try{codec_tests();session_tests();tls_tests();std::cout<<"PASS "<<assertions<<" HOST protocol/policy/real Windows Schannel TCP assertions; no SPORE process started.\n";return 0;}catch(const std::exception& e){std::cerr<<"FAIL after "<<assertions<<" assertions: "<<e.what()<<'\n';return 1;}}
